/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorySystem;

import org.netbeans.lib.awtextra.AbsoluteLayout;

import java.awt.*;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *This method is used to create GUI and
 * make the GUI work by calling different methods from different class.
 * 
 */
public class MainFrame extends javax.swing.JFrame {
    //-------user input----//
    String modelNamee;
    String color;
    String noOfGears;
    int range;
    String discOption;
    String fuleDeliverySystem;
    String breakingSystem;
    String fuleTankCapacity;
    String price;
    String type;
    String cateogary;
    
    
    
    // 2D array to store all data of user input
    ArrayList<ArrayList<String>> orgArray = new ArrayList();
    
    // it contain change panel method (Creating AppliancesInfo Object)
    AppliancesInfo appliancesInfoObj = new AppliancesInfo();
    
    // it contain file reader method and this display the read file ((Creating ImportTxtFile Object))
    ImportTxtFile importTxtFileObj = new ImportTxtFile();
    
    // this class contain the method for validation 
    Validation validationObj = new Validation();
    
    // this class contain method to remove selected data from array list and JTable
    RemoveUserData removeUserDataObj = new RemoveUserData();
    
    // This class contain the method for Linear search
    LinearSearch linearSearchObj = new LinearSearch();
    
    // this method contain the method to save data
    SaveFile SaveFileObj = new SaveFile();
    
    // This class contain the method for Binary search
    BinarySearch BinarySearchObj = new  BinarySearch();
    
    public MainFrame() {
        initComponents();
        // comany name panel transparent
        companyNamePanel.setBackground(new Color(0,0,0,0)); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rangebuttonGroup = new javax.swing.ButtonGroup();
        discOptionbuttonGroup = new javax.swing.ButtonGroup();
        fuleDeliverySystembuttonGroup = new javax.swing.ButtonGroup();
        breakingSystembuttonGroup = new javax.swing.ButtonGroup();
        searchDataDialog = new javax.swing.JDialog();
        searchDataDialogPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchValueTable = new javax.swing.JTable();
        SearchDialogBoxSearchCatogery = new javax.swing.JLabel();
        searchDialogBoxTitleLabel = new javax.swing.JLabel();
        binaySearchDialog = new javax.swing.JDialog();
        binarySearchDataDialogPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        binSearchValueTable = new javax.swing.JTable();
        searchDialogBoxTitleLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        holderPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        companyNamePanel = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        inventeryButton1 = new javax.swing.JButton();
        footerLabel = new javax.swing.JLabel();
        backgroundImageLabel = new javax.swing.JLabel();
        inventoryPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        categarySearchLabel = new javax.swing.JLabel();
        buttonSearchByCategory = new javax.swing.JButton();
        priceSearchLabel = new javax.swing.JLabel();
        searchPrice = new javax.swing.JTextField();
        buttonSearchByPrice = new javax.swing.JButton();
        vechTitle = new javax.swing.JLabel();
        changeVehicleButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        backBthLabel = new javax.swing.JLabel();
        bodyPanel1 = new javax.swing.JPanel();
        bodyPanel2 = new javax.swing.JPanel();
        rangeRadioButton120 = new javax.swing.JRadioButton();
        rangeRadioButton200 = new javax.swing.JRadioButton();
        rangeRadioButton150 = new javax.swing.JRadioButton();
        rangeRadioButton250 = new javax.swing.JRadioButton();
        colorLabel = new javax.swing.JLabel();
        colorTextFiled1 = new javax.swing.JTextField();
        noOfGearsLabel = new javax.swing.JLabel();
        ComboBoxNoOfGears1 = new javax.swing.JComboBox<>();
        modelNameLabel = new javax.swing.JLabel();
        rangeLabel = new javax.swing.JLabel();
        modelNameTextField = new javax.swing.JTextField();
        discOptionLabel = new javax.swing.JLabel();
        discOptionRadioButton1 = new javax.swing.JRadioButton();
        discOptionRadioButton2 = new javax.swing.JRadioButton();
        fuleDeliverySystemLabel = new javax.swing.JLabel();
        fuleDeliverySystemRadioButton1 = new javax.swing.JRadioButton();
        fuleDeliverySystemRadioButton2 = new javax.swing.JRadioButton();
        breakingLabel = new javax.swing.JLabel();
        breakingSystemRadioButton1 = new javax.swing.JRadioButton();
        breakingSystemRadioButton2 = new javax.swing.JRadioButton();
        fuleTankCapacityTextField = new javax.swing.JTextField();
        fuleCapacityLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cateogaryLabel = new javax.swing.JLabel();
        cateogaryComboBox = new javax.swing.JComboBox<>();
        removeAllButton = new javax.swing.JButton();
        searchCateogaryComboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openFileMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        back = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        userManualMenuItem = new javax.swing.JMenuItem();

        searchDataDialog.setBackground(new java.awt.Color(255, 234, 157));
        searchDataDialog.setMinimumSize(new java.awt.Dimension(1003, 372));

        searchDataDialogPanel.setBackground(new java.awt.Color(255, 234, 157));

        searchValueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Cateogary", "Vehicle ID.", "Model Name", "Range/Displacement", "Color", "No. of gears", "Disc Option", "Fuel Delivery System", "Breaking System", "Fuel Tank Capacity", "Price(IDR.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(searchValueTable);

        SearchDialogBoxSearchCatogery.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        SearchDialogBoxSearchCatogery.setText("jLabel1");

        searchDialogBoxTitleLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        searchDialogBoxTitleLabel.setText("Dealer Duniawi  Ltd.");

        javax.swing.GroupLayout searchDataDialogPanelLayout = new javax.swing.GroupLayout(searchDataDialogPanel);
        searchDataDialogPanel.setLayout(searchDataDialogPanelLayout);
        searchDataDialogPanelLayout.setHorizontalGroup(
            searchDataDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchDataDialogPanelLayout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addGroup(searchDataDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchDataDialogPanelLayout.createSequentialGroup()
                        .addComponent(searchDialogBoxTitleLabel)
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchDataDialogPanelLayout.createSequentialGroup()
                        .addComponent(SearchDialogBoxSearchCatogery)
                        .addGap(458, 458, 458))))
        );
        searchDataDialogPanelLayout.setVerticalGroup(
            searchDataDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchDataDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchDialogBoxTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchDialogBoxSearchCatogery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout searchDataDialogLayout = new javax.swing.GroupLayout(searchDataDialog.getContentPane());
        searchDataDialog.getContentPane().setLayout(searchDataDialogLayout);
        searchDataDialogLayout.setHorizontalGroup(
            searchDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchDataDialogPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchDataDialogLayout.setVerticalGroup(
            searchDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchDataDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        binaySearchDialog.setMinimumSize(new java.awt.Dimension(1003, 372));

        binarySearchDataDialogPanel.setBackground(new java.awt.Color(255, 234, 157));

        binSearchValueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Cateogary", "Vehicle ID.", "Model Name", "Range/Displacement", "Color", "No. of gears", "Disc Option", "Fuel Delivery System", "Breaking System", "Fuel Tank Capacity", "Price(IDR.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(binSearchValueTable);

        searchDialogBoxTitleLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        searchDialogBoxTitleLabel1.setText("Dealer duniawi Pvt. Ltd.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Two wheller with the searched price ");

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout binarySearchDataDialogPanelLayout = new javax.swing.GroupLayout(binarySearchDataDialogPanel);
        binarySearchDataDialogPanel.setLayout(binarySearchDataDialogPanelLayout);
        binarySearchDataDialogPanelLayout.setHorizontalGroup(
            binarySearchDataDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(binarySearchDataDialogPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(binarySearchDataDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchDialogBoxTitleLabel1)
                    .addGroup(binarySearchDataDialogPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        binarySearchDataDialogPanelLayout.setVerticalGroup(
            binarySearchDataDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, binarySearchDataDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchDialogBoxTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(binarySearchDataDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout binaySearchDialogLayout = new javax.swing.GroupLayout(binaySearchDialog.getContentPane());
        binaySearchDialog.getContentPane().setLayout(binaySearchDialogLayout);
        binaySearchDialogLayout.setHorizontalGroup(
            binaySearchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(binarySearchDataDialogPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        binaySearchDialogLayout.setVerticalGroup(
            binaySearchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(binarySearchDataDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1252, 704));
        setResizable(false);

        holderPanel.setBackground(new java.awt.Color(0, 0, 0));
        holderPanel.setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new AbsoluteLayout ());

        companyNamePanel.setBackground(new java.awt.Color(255, 234, 167));

        nameLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 100)); // NOI18N
        nameLabel1.setText("Dealer");

        nameLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 100)); // NOI18N
        nameLabel2.setText("Duniawi");

        nameLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 100)); // NOI18N
        nameLabel3.setText("Jaya");

        messageLabel.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        messageLabel.setText("Selamat datang di sistem pergudangan Dealer Duniawi Jaya.");

        javax.swing.GroupLayout companyNamePanelLayout = new javax.swing.GroupLayout(companyNamePanel);
        companyNamePanel.setLayout(companyNamePanelLayout);
        companyNamePanelLayout.setHorizontalGroup(
            companyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyNamePanelLayout.createSequentialGroup()
                .addComponent(nameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(companyNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(companyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel2)
                    .addComponent(nameLabel1)
                    .addComponent(messageLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        companyNamePanelLayout.setVerticalGroup(
            companyNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyNamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel)
                .addGap(59, 59, 59))
        );

        mainPanel.add(companyNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 396));

        inventeryButton1.setBackground(new java.awt.Color(241, 209, 181));
        inventeryButton1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        inventeryButton1.setText("Inventory System");
        inventeryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventeryButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(inventeryButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 708, -1));

        footerLabel.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        footerLabel.setText("This is the Inventory System to record Stock of Two-Wheeler Showroom.");
        mainPanel.add(footerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, -1, -1));

        backgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wpp.jpg"))); // NOI18N
        backgroundImageLabel.setText("jLabel1");
        backgroundImageLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        mainPanel.add(backgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 680));

        holderPanel.add(mainPanel, "card2");

        inventoryPanel.setBackground(new java.awt.Color(255, 234, 167));
        inventoryPanel.setMinimumSize(new java.awt.Dimension(1252, 683));

        displayTable.setAutoCreateRowSorter(true);
        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Category", "Vehicle ID.", "Model Name", "Range/ Displacement", "Color", "No.of gears", "Disc Option", "Fuel Delivery System", "Breaking System", "Fuel Tank capacity", "Price (IDR.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayTable.setToolTipText("");
        jScrollPane2.setViewportView(displayTable);

        categarySearchLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        categarySearchLabel.setText("Category");

        buttonSearchByCategory.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonSearchByCategory.setText("Search By Category");
        buttonSearchByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchByCategoryActionPerformed(evt);
            }
        });

        priceSearchLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        priceSearchLabel.setText("Price");

        searchPrice.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        buttonSearchByPrice.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonSearchByPrice.setText("Search By Price");
        buttonSearchByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchByPriceActionPerformed(evt);
            }
        });

        vechTitle.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        vechTitle.setText("Bikes");

        changeVehicleButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        changeVehicleButton.setText("Switch Vechicle");
        changeVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeVehicleButtonMouseClicked(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        titleLabel.setText(" ");

        backBthLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back_to_6px.png"))); // NOI18N
        backBthLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBthLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBthLabelMouseClicked(evt);
            }
        });

        bodyPanel1.setBackground(new java.awt.Color(255, 234, 167));
        bodyPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        bodyPanel2.setBackground(new java.awt.Color(255, 234, 167));
        bodyPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rangebuttonGroup.add(rangeRadioButton120);
        rangeRadioButton120.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        rangeRadioButton120.setText("120 cc");

        rangebuttonGroup.add(rangeRadioButton200);
        rangeRadioButton200.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        rangeRadioButton200.setText("200 cc");

        rangebuttonGroup.add(rangeRadioButton150);
        rangeRadioButton150.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        rangeRadioButton150.setText("150 cc");

        rangebuttonGroup.add(rangeRadioButton250);
        rangeRadioButton250.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        rangeRadioButton250.setText("250 cc");

        colorLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        colorLabel.setText("Color");

        colorTextFiled1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        noOfGearsLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        noOfGearsLabel.setText("No. of Gears");

        ComboBoxNoOfGears1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ComboBoxNoOfGears1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6" }));

        modelNameLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        modelNameLabel.setText("Model Name");

        rangeLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        rangeLabel.setText("Range / Displacement");

        modelNameTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        discOptionLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        discOptionLabel.setText("Disc Option");

        discOptionbuttonGroup.add(discOptionRadioButton1);
        discOptionRadioButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        discOptionRadioButton1.setText("Single Disc");

        discOptionbuttonGroup.add(discOptionRadioButton2);
        discOptionRadioButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        discOptionRadioButton2.setText("Double Disc");

        fuleDeliverySystemLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fuleDeliverySystemLabel.setText("Fuel Delivery System");

        fuleDeliverySystembuttonGroup.add(fuleDeliverySystemRadioButton1);
        fuleDeliverySystemRadioButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fuleDeliverySystemRadioButton1.setText("karburator");

        fuleDeliverySystembuttonGroup.add(fuleDeliverySystemRadioButton2);
        fuleDeliverySystemRadioButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        fuleDeliverySystemRadioButton2.setText("Fuel injection (FI)");

        breakingLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        breakingLabel.setText("Breaking System");

        breakingSystembuttonGroup.add(breakingSystemRadioButton1);
        breakingSystemRadioButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        breakingSystemRadioButton1.setText("ABS");

        breakingSystembuttonGroup.add(breakingSystemRadioButton2);
        breakingSystemRadioButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        breakingSystemRadioButton2.setText("None ABS");

        fuleTankCapacityTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        fuleCapacityLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fuleCapacityLabel.setText("Fuel Tank Capacity");

        priceLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        priceLabel.setText("Price (IDR.)");

        priceTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        addButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cateogaryLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cateogaryLabel.setForeground(new java.awt.Color(51, 51, 51));
        cateogaryLabel.setText("Category");

        cateogaryComboBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cateogaryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Bajaj", "Aprilla", "Benelli", "Suzuki", "Yamaha"}));

        removeAllButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        removeAllButton.setText("Remove All");
        removeAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyPanel2Layout = new javax.swing.GroupLayout(bodyPanel2);
        bodyPanel2.setLayout(bodyPanel2Layout);
        bodyPanel2Layout.setHorizontalGroup(
            bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyPanel2Layout.createSequentialGroup()
                                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rangeRadioButton150, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rangeRadioButton250, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                                        .addComponent(modelNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(modelNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89)
                                .addComponent(colorLabel)
                                .addGap(379, 379, 379))
                            .addGroup(bodyPanel2Layout.createSequentialGroup()
                                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(discOptionLabel)
                                    .addComponent(fuleCapacityLabel)
                                    .addComponent(rangeLabel))
                                .addGap(35, 35, 35)
                                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                                        .addComponent(discOptionRadioButton2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(bodyPanel2Layout.createSequentialGroup()
                                                .addComponent(fuleTankCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(155, 155, 155))
                                            .addGroup(bodyPanel2Layout.createSequentialGroup()
                                                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(discOptionRadioButton1)
                                                    .addComponent(rangeRadioButton200, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rangeRadioButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(122, 122, 122)
                                                .addComponent(fuleDeliverySystemLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanel2Layout.createSequentialGroup()
                                                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(colorTextFiled1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cateogaryLabel)
                                                            .addComponent(noOfGearsLabel)))
                                                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                                                        .addComponent(fuleDeliverySystemRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                                        .addComponent(breakingLabel)))
                                                .addGap(5, 5, 5))
                                            .addGroup(bodyPanel2Layout.createSequentialGroup()
                                                .addComponent(fuleDeliverySystemRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(priceLabel)))))))
                        .addGap(7, 7, 7)
                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(breakingSystemRadioButton1)
                            .addComponent(breakingSystemRadioButton2)
                            .addComponent(ComboBoxNoOfGears1, 0, 221, Short.MAX_VALUE)
                            .addComponent(cateogaryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(removeAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        bodyPanel2Layout.setVerticalGroup(
            bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rangeRadioButton120)
                                .addComponent(rangeLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rangeRadioButton150)
                                .addComponent(colorLabel))))
                    .addGroup(bodyPanel2Layout.createSequentialGroup()
                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cateogaryLabel)
                            .addComponent(cateogaryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorTextFiled1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(noOfGearsLabel)
                                .addComponent(ComboBoxNoOfGears1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(4, 4, 4)
                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rangeRadioButton200)
                    .addComponent(rangeRadioButton250))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discOptionRadioButton1)
                    .addComponent(discOptionLabel)
                    .addComponent(fuleDeliverySystemLabel)
                    .addComponent(fuleDeliverySystemRadioButton1)
                    .addComponent(breakingSystemRadioButton1)
                    .addComponent(breakingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discOptionRadioButton2)
                    .addComponent(fuleDeliverySystemRadioButton2)
                    .addComponent(breakingSystemRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(priceTextField)
                    .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fuleTankCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fuleCapacityLabel)
                        .addComponent(priceLabel)))
                .addGap(32, 32, 32)
                .addGroup(bodyPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(saveButton)
                    .addComponent(removeButton)
                    .addComponent(clearButton)
                    .addComponent(removeAllButton))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout bodyPanel1Layout = new javax.swing.GroupLayout(bodyPanel1);
        bodyPanel1.setLayout(bodyPanel1Layout);
        bodyPanel1Layout.setHorizontalGroup(
            bodyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bodyPanel1Layout.setVerticalGroup(
            bodyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bodyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchCateogaryComboBox.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        searchCateogaryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Bajaj", "Aprilla", "Benelli", "Suzuki", "Yamaha" }));

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryPanelLayout.createSequentialGroup()
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bodyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vechTitle)
                        .addGap(425, 425, 425)
                        .addComponent(changeVehicleButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inventoryPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(categarySearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCateogaryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSearchByCategory)
                        .addGap(372, 372, 372)
                        .addComponent(priceSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inventoryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleLabel)
                        .addGap(259, 259, 259)))
                .addContainerGap())
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCateogaryComboBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categarySearchLabel)
                        .addComponent(priceSearchLabel)
                        .addComponent(searchPrice)
                        .addComponent(buttonSearchByPrice)
                        .addComponent(buttonSearchByCategory)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vechTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeVehicleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        holderPanel.add(inventoryPanel, "card3");

        getContentPane().add(holderPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        openFileMenuItem.setText("Open File");
        openFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openFileMenuItem);

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        fileMenu.add(back);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        jMenu2.setText("Help");

        userManualMenuItem.setText("User Manual");
        userManualMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManualMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(userManualMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //----------change panel from main panel to inventory panel-----------------//
    private void inventeryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventeryButton1ActionPerformed
        appliancesInfoObj.showComponent(holderPanel, inventoryPanel);
    }//GEN-LAST:event_inventeryButton1ActionPerformed

    
    
    
    //-----------------------Search the required cateagory using  Linear search--------//
    private void buttonSearchByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchByCategoryActionPerformed
        //foundSearch is used to track if search catteogary found or not
        int foundSearch = linearSearchObj.linearSearch(searchCateogaryComboBox, orgArray, searchDataDialog, searchValueTable);
        SearchDialogBoxSearchCatogery.setText(searchCateogaryComboBox.getSelectedItem().toString());
        // display table if searched cateogary found only
        if (foundSearch!= 0) {
            searchDataDialog.setVisible(true);
        } 
        else {
            JOptionPane.showMessageDialog(this, "Searched Cateogary not found !!");
        }
    }//GEN-LAST:event_buttonSearchByCategoryActionPerformed

    
    
    
    //-----------------Change the vehicle type----------------------------------//
    private void changeVehicleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeVehicleButtonMouseClicked
        //it will change the vechicle title or type
        if ("Bikes".equals(vechTitle.getText())) {
            vechTitle.setText("");
            vechTitle.setText("Scooter");
            ComboBoxNoOfGears1.disable();
        } else {
            vechTitle.setText("");
            vechTitle.setText("Bikes");
            ComboBoxNoOfGears1.enable();
        }
    }//GEN-LAST:event_changeVehicleButtonMouseClicked

    
    
    //-----------------------get back to main panel--------------------//
    private void backBthLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBthLabelMouseClicked
        appliancesInfoObj.showComponent(holderPanel, mainPanel);
    }//GEN-LAST:event_backBthLabelMouseClicked

    
    
    
    //---------------------------Adding user value in table and 2D array------//
    String isEmpty;// check is user input field is empty
    String isInt;// if tank capacity and price Int
    String vehicleId;
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        //if JTable already have data of txt file
        if(importTxtFileObj.tableHave == "fileData"){
            JOptionPane.showMessageDialog(this, "Please click remove all button");
        }
        
        
        else{
            // Model Name
            modelNamee = modelNameTextField.getText();
            // Color
            color = colorTextFiled1.getText();
            // type
            type = vechTitle.getText();
            // cateogary or company name 
            cateogary = cateogaryComboBox.getSelectedItem().toString();
           // fuel tank capacity
            fuleTankCapacity =fuleTankCapacityTextField.getText();
            // Price
            price = priceTextField.getText();
            
            //___set no.of gear none if vechicle type is Scooter__________//
            if(type.equals("Bikes")){
                // no. of Gears (Bike) 
                noOfGears = ComboBoxNoOfGears1.getSelectedItem().toString();
            }
            else if(type.equals("Scooter")){
                noOfGears ="None";
            }
            
            //_____________Range___________________//
            if (rangeRadioButton120.isSelected()) {
                range = 120;
            } else if (rangeRadioButton150.isSelected()) {
                range = 150;
            } else if (rangeRadioButton200.isSelected()) {
                range = 200;
            } else if (rangeRadioButton250.isSelected()) {
                range = 250;
            }

            //_____________Disc Option_________________/
            if (discOptionRadioButton1.isSelected()) {
                discOption = "Single Disc";
            } else if (discOptionRadioButton2.isSelected()) {
                discOption = "Double Disc";
            }

            //________________fuelDeliverySystem_____________//
            if (fuleDeliverySystemRadioButton1.isSelected()) {
                fuleDeliverySystem = "Carburetor";
            } else if (fuleDeliverySystemRadioButton2.isSelected()) {
                fuleDeliverySystem = "Fuel injection (FI)";
            }

            //_________________breakingSystem_____________//
            if (breakingSystemRadioButton1.isSelected()) {
                breakingSystem = "ABS";
            } else if (breakingSystemRadioButton2.isSelected()) {
                breakingSystem = "None ABS";
            }
            
            
            //____________ Check if user input is empty or not________________//
            //___________(checkEmpty is method of validation class)__________//
            isEmpty = validationObj.checkEmpty(modelNamee, color, type, range, discOption, fuleDeliverySystem, breakingSystem, fuleTankCapacity, price);
            
            if(!isEmpty.equals("no")){
                JOptionPane.showMessageDialog(this, "Please insert "+isEmpty+" !!!");
            }
            //__if not empty
            else if(isEmpty.equals("no")){
                
                //______Check if fuel tank and price is int_______________//
                //__(checkInteger is method of validation class)
                isInt = validationObj.checkInteger(fuleTankCapacity, price);
                
                if(!isInt.equals("no")){
                    JOptionPane.showMessageDialog(this, "Fuel Tank Capacity and Price(IDR.)" + "\n" + "can not be String!!!");
                }
                
                //if every thing is ok
                else if(isInt.equals("no")){
                    //_______Create Vechicle ID____________//
                    //__(createID method is in validation class)
                    vehicleId = validationObj.createId(type);
                    
                    //______add user data to array______//(validation class method) 
                    validationObj.insertIntoArray(type, cateogary,vehicleId, modelNamee,range, color, noOfGears, discOption,
                            fuleDeliverySystem, breakingSystem, fuleTankCapacity,price, orgArray);
                    
                    //__ adding array list in JTable__//(methos is in ApplicationInfo class)
                    appliancesInfoObj.addToTable(displayTable, orgArray);
                    
                    JOptionPane.showMessageDialog(this, "Registered Sucessfully !!!");
                }
            }
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    
    
    
    
    //---------------------Remove selected data from table and array---------//
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if(displayTable.getSelectedRow() == -1 ){// if no row select
            JOptionPane.showMessageDialog(this, "Please select row !!!");
        }
        else if(displayTable.getSelectedRowCount()> 1){// if many row saved
            JOptionPane.showMessageDialog(this, "Please select only one row !!");
        }
        else{
            //--- remove data from table and 2Darray(removeData method is in removeUserData class)
            removeUserDataObj.removeData(displayTable, orgArray);
            JOptionPane.showMessageDialog(this, "Row removed sucessfully !!");
        }
        
    }//GEN-LAST:event_removeButtonActionPerformed

    
    
    
    
    //--------------------------Clear Text Field------------------------------//
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
       // model name
        modelNameTextField.setText("");
        // Color
        colorTextFiled1.setText(""); 
        // fuel tank capacity
        fuleTankCapacityTextField.setText(""); 
        // price
        priceTextField.setText(""); 
        // breaking system
        breakingSystembuttonGroup.clearSelection(); 
        breakingSystem = null;
        // fuel delivery system
        fuleDeliverySystembuttonGroup.clearSelection();
        fuleDeliverySystem = null;
        // disc option
        discOptionbuttonGroup.clearSelection();
        discOption = null;
        // range
        rangebuttonGroup.clearSelection(); 
        range = 0;
    }//GEN-LAST:event_clearButtonActionPerformed

    
    //----------------save file button-------------------//
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
       //calling method of same class to save all data 
        saveAllData();
    }//GEN-LAST:event_saveButtonActionPerformed

    
    //-------------------back to main frame____(Menu bar)-----------------//
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        appliancesInfoObj.showComponent(holderPanel, mainPanel);
    }//GEN-LAST:event_backActionPerformed

    
    
    
    //---Opening text file and displaying in table Also storing in orgArray------//
    private void openFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileMenuItemActionPerformed
        if(displayTable.getRowCount() != 0){
            JOptionPane.showMessageDialog(this, "Please click remove all button");
        }
        else{
            
            // change panel to inventory if not in inventory panel
            appliancesInfoObj.showComponent(holderPanel, inventoryPanel);
            //import from text file and inserting in table
            importTxtFileObj.openFile(inventoryPanel,displayTable, orgArray);
        }
        
    }//GEN-LAST:event_openFileMenuItemActionPerformed

    
    
        
    //----------------Remove all data from 2D array and JTable-------------------//
    private void removeAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllButtonActionPerformed
        // TODO add your handling code here:
        orgArray.clear();
        appliancesInfoObj.addToTable(displayTable, orgArray);
        JOptionPane.showMessageDialog(this, "All data removed");
        importTxtFileObj.tableHave = "own";
        
    }//GEN-LAST:event_removeAllButtonActionPerformed

    
    
    
    //----------------------------exit button in menu bar----------------------//
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // closing window (Menu item)
        System.exit(0);   
    }//GEN-LAST:event_exitMenuItemActionPerformed

    
    
    
    
    //----------save table data in text document (Menu Item)-----------------//
    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        saveAllData();
        
    }//GEN-LAST:event_saveMenuItemActionPerformed

    
    
    
    //------------------------opening user manuanl---------------------------------//
    private void userManualMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManualMenuItemActionPerformed
        // TODO add your handling code here:
        File file=new File("..//UserManual.pdf");
        try {
            Desktop.getDesktop().open(file);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "File not found");
        }
    }//GEN-LAST:event_userManualMenuItemActionPerformed

    
    
    
    
    //-----------------------------Search price (Binary Search)--------------------//
    private void buttonSearchByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchByPriceActionPerformed
       String searchedPrice = " ";
       String findSearchPrice = "";
       int findSearchPriceNum = 0;
       findSearchPrice = searchPrice.getText();
       if (findSearchPrice.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Please enter the price!!");
       }
       
       if (!findSearchPrice.isEmpty()) {
           searchedPrice = BinarySearchObj.searchByPrice(displayTable, findSearchPrice,
                           findSearchPriceNum, binaySearchDialog, binSearchValueTable, searchPrice, jLabelPrice);
           //System.out.println("se "+searchedPrice);
           if("notExist".equals(searchedPrice)){
               JOptionPane.showMessageDialog(binaySearchDialog, "Two wheller with such price does not exist!!!");
               //searchedPrice ="";
           }
           else if("notContain".equals(searchedPrice)){
               JOptionPane.showMessageDialog(this, "The table does not contain any data!!!");
               //searchedPrice= "";
           }
           else if("notInNumerical".equals(searchedPrice)){
               JOptionPane.showMessageDialog(this, "Please enter the price in numberical form!!");
               //searchedPrice ="";
           }
         
       }
    }//GEN-LAST:event_buttonSearchByPriceActionPerformed
    
    
     
    
    
    
    //------------save the data to text documenet file-----//
    public void saveAllData(){
        //open file chooser
        JFileChooser saveFileChooser = new JFileChooser();
        // set file extension
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES (.txt)", "txt", "text");
        saveFileChooser.setFileFilter(filter);
        // set file chooser title
        saveFileChooser.setDialogTitle("Specify a file to save");
        // checking if file is selected
        int userSelection = saveFileChooser.showSaveDialog(this);
         
        String dataTosave = SaveFileObj.save(saveFileChooser, userSelection, displayTable);
        if("saved".equals(dataTosave)){
            JOptionPane.showMessageDialog(this, "Saved in selected File !!!");
        }
           
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxNoOfGears1;
    private javax.swing.JLabel SearchDialogBoxSearchCatogery;
    private javax.swing.JButton addButton;
    private javax.swing.JMenuItem back;
    private javax.swing.JLabel backBthLabel;
    private javax.swing.JLabel backgroundImageLabel;
    private javax.swing.JTable binSearchValueTable;
    private javax.swing.JPanel binarySearchDataDialogPanel;
    private javax.swing.JDialog binaySearchDialog;
    private javax.swing.JPanel bodyPanel1;
    private javax.swing.JPanel bodyPanel2;
    private javax.swing.JLabel breakingLabel;
    private javax.swing.JRadioButton breakingSystemRadioButton1;
    private javax.swing.JRadioButton breakingSystemRadioButton2;
    private javax.swing.ButtonGroup breakingSystembuttonGroup;
    private javax.swing.JButton buttonSearchByCategory;
    private javax.swing.JButton buttonSearchByPrice;
    private javax.swing.JLabel categarySearchLabel;
    private javax.swing.JComboBox<String> cateogaryComboBox;
    private javax.swing.JLabel cateogaryLabel;
    private javax.swing.JButton changeVehicleButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextFiled1;
    private javax.swing.JPanel companyNamePanel;
    private javax.swing.JLabel discOptionLabel;
    private javax.swing.JRadioButton discOptionRadioButton1;
    private javax.swing.JRadioButton discOptionRadioButton2;
    private javax.swing.ButtonGroup discOptionbuttonGroup;
    private javax.swing.JTable displayTable;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel footerLabel;
    private javax.swing.JLabel fuleCapacityLabel;
    private javax.swing.JLabel fuleDeliverySystemLabel;
    private javax.swing.JRadioButton fuleDeliverySystemRadioButton1;
    private javax.swing.JRadioButton fuleDeliverySystemRadioButton2;
    private javax.swing.ButtonGroup fuleDeliverySystembuttonGroup;
    private javax.swing.JTextField fuleTankCapacityTextField;
    private javax.swing.JPanel holderPanel;
    private javax.swing.JButton inventeryButton1;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel modelNameLabel;
    private javax.swing.JTextField modelNameTextField;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel noOfGearsLabel;
    private javax.swing.JMenuItem openFileMenuItem;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceSearchLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel rangeLabel;
    private javax.swing.JRadioButton rangeRadioButton120;
    private javax.swing.JRadioButton rangeRadioButton150;
    private javax.swing.JRadioButton rangeRadioButton200;
    private javax.swing.JRadioButton rangeRadioButton250;
    private javax.swing.ButtonGroup rangebuttonGroup;
    private javax.swing.JButton removeAllButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JComboBox<String> searchCateogaryComboBox;
    public javax.swing.JDialog searchDataDialog;
    private javax.swing.JPanel searchDataDialogPanel;
    private javax.swing.JLabel searchDialogBoxTitleLabel;
    private javax.swing.JLabel searchDialogBoxTitleLabel1;
    private javax.swing.JTextField searchPrice;
    private javax.swing.JTable searchValueTable;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JMenuItem userManualMenuItem;
    private javax.swing.JLabel vechTitle;


    // End of variables declaration//GEN-END:variables
}
